
language: python
cache: pip

python:
    - "3.5"
    - "3.6"

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
    - pip install flake8

before_script:
    - flake8 cyberstarx --count --max-line-length=127 --statistics
script:
    - python setup.py test

notifications:
    on_success: change

on_failure: change  # `always` will be the setting once code changes slow down